### ISSUE TITLE
About  the Skeletonization

### ISSUE THREAD

**Issue by hanhantie233** [eiiijiiiy/sobss#1]
Sir, When I run the Skeletonization , the following errors will occur:
![image](https://github.com/eiiijiiiy/sobss/assets/130548715/f73e3012-ed90-4f9c-9213-44a1dfef3cb8)

Why the "num vertical" is 0?

**Comment by eiiijiiiy** [comment]
Thanks for your interest! Would you mind share the point cloud in this case and allow me some time to test and figure out the issue?

**Comment by hanhantie233** [comment]
> Thanks for your interest! Would you mind share the point cloud in this case and allow me some time to test and figure out the issue?
Thank you very much for your help. The file has been saved to Google Drive:https://drive.google.com/file/d/11rgveIcgzL_34H2JzLzD-80WvvGIcUja/view?usp=sharing

**Comment by eiiijiiiy** [comment]
Hey hanhantie233, I just looked at the test point cloud. There are two issues here. 

1. Our algorithm requires an oriented point cloud. The given pcd have a vertex normal property, but all the normals are zero. That's why the skeletonize step cannot collect any BSS atom and the bss_atom.txt is empty.
2. The point cloud itself is a bit sparse and incomplete on the building facades. I think it would be non-trivial to estimate the normals correctly for the sample. Furthermore, our algorithm is not well-suited for reconstructing from point clouds that are sparse and incomplete, particularly when the issues occure on the facades. Sorry for that!

Given the point cloud appears to be an airbrone point cloud, with dense sampling on the roof but sparse on the facades, I believe there are some other more suitable reconstruction methods for that. One possibility could be City3D, which can take both 3D airbrone LiDAR and 2D footprint of a building as input to reconstruction it. 

Please let me know if you have any other questions.

**Comment by hanhantie233** [comment]
> Hey hanhantie233, I just looked at the test point cloud. There are two issues here.
> 
> 1. Our algorithm requires an oriented point cloud. The given pcd have a vertex normal property, but all the normals are zero. That's why the skeletonize step cannot collect any BSS atom and the bss_atom.txt is empty.
> 2. The point cloud itself is a bit sparse and incomplete on the building facades. I think it would be non-trivial to estimate the normals correctly for the sample. Furthermore, our algorithm is not well-suited for reconstructing from point clouds that are sparse and incomplete, particularly when the issues occure on the facades. Sorry for that!
> 
> Given the point cloud appears to be an airbrone point cloud, with dense sampling on the roof but sparse on the facades, I believe there are some other more suitable reconstruction methods for that. One possibility could be City3D, which can take both 3D airbrone LiDAR and 2D footprint of a building as input to reconstruction it.
> 
> Please let me know if you have any other questions.

Your algorithm has been very helpful to me, and I greatly appreciate your response. I will try to solve the problem according to the method you provided. At the moment, I don't have any other questions.
